/**
 * List of all barangays in Puerto Princesa City, Palawan
 */
export const PUERTO_PRINCESA_BARANGAYS = [
  "Bagong Pag-asa (Poblacion)",
  "Bagong Sikat (Poblacion)",
  "Bagong Silang (Poblacion)",
  "Bancao-bancao",
  "Irawan",
  "Kalipay (Poblacion)",
  "Liwanag (Poblacion)",
  "Mabuhay (Poblacion)",
  "Magkakaibigan (Poblacion)",
  "Maligaya (Poblacion)",
  "Mandaragat",
  "Manggahan (Poblacion)",
  "Maningning (Poblacion)",
  "Masigla (Poblacion)",
  "Masikap (Poblacion)",
  "Masipag (Poblacion)",
  "Matahimik (Poblacion)",
  "Matiyaga (Poblacion)",
  "Maunlad (Poblacion)",
  "Milagrosa (Poblacion)",
  "Model (Poblacion)",
  "Pagkakaisa (Poblacion)",
  "Princesa (Poblacion)",
  "San Jose",
  "San Manuel",
  "San Miguel",
  "San Pedro",
  "Santa Lucia (Poblacion)",
  "Santa Monica",
  "Seaside (Poblacion)",
  "Sicsican",
  "Tagburos",
  "Tagumpay (Poblacion)",
  "Tanglaw (Poblacion)",
  "Tiniguiban",
];